# Generated by Django 5.2.7 on 2025-10-17 07:26

import django.db.models.deletion
from django.db import migrations, models
import random  # 추가

def generate_numeric_code(length=5):
    return f"{random.randint(0, 10**length - 1):0{length}d}"

def create_initial_groupcode(apps, schema_editor):
    GroupCode = apps.get_model('service', 'GroupCode')

    initial_data = [
        ("금속캔_철캔_1", "steel_can1"),
        ("금속캔_철캔_2", "steel_can2"),
        ("금속캔_철캔_3", "steel_can3"),
        ("금속캔_알루미늄캔_1", "aluminum_can1"),
        ("금속캔_알루미늄캔_2", "aluminum_can2"),
        ("종이_001_종이_1", "paper1"),
        ("종이_001_종이_2", "paper2"),
        ("페트병_001_무색단일_1", "pet_clear_single1"),
        ("페트병_001_무색단일_2", "pet_clear_single2"),
        ("페트병_001_무색단일_3", "pet_clear_single3"),
        ("페트병_002_유색단일_1", "pet_colored_single1"),
        ("페트병_002_유색단일_2", "pet_colored_single2"),
        ("페트병_002_유색단일_3", "pet_colored_single3"),
        ("플라스틱_001_PE_1", "plastic_pe1"),
        ("플라스틱_001_PE_2", "plastic_pe2"),
        ("플라스틱_002_PP_1", "plastic_pp1"),
        ("플라스틱_002_PP_2", "plastic_pp2"),
        ("플라스틱_002_PP_3", "plastic_pp3"),
        ("플라스틱_003_PS_1", "plastic_ps1"),
        ("플라스틱_003_PS_2", "plastic_ps2"),
        ("플라스틱_003_PS_3", "plastic_ps3"),
        ("스티로폼_001_스티로폼_1", "styrofoam1"),
        ("스티로폼_001_스티로폼_2", "styrofoam2"),
        ("비닐_001_비닐", "vinyl"),
        ("유리병_001_갈색", "glass_brown"),
        ("유리병_002_녹색", "glass_green"),
        ("유리병_003_투명", "glass_clear"),
        ("건전지_001_건전지", "battery"),
        ("형광등_001_형광등", "fluorescent_lamp"),
    ]

    for name, code in initial_data:
        while True:
            numeric_code = generate_numeric_code(5)
            if not GroupCode.objects.filter(numeric_code=numeric_code).exists():
                break
        GroupCode.objects.get_or_create(
            name=name,
            defaults={
                "code": code,
                "numeric_code": numeric_code,
                "desc": f"{name} 설명"
            }
        )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='코드명(한글)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='기존 코드명')),
                ('numeric_code', models.CharField(editable=False, max_length=5, unique=True, verbose_name='문자형 숫자 코드')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '분류 코드',
                'verbose_name_plural': '분류 코드 목록',
                'db_table': 'group_code',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecyclableResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PREDICTED_CLASS', models.CharField(blank=True, max_length=100, null=True, verbose_name='생활쓰레기 구분')),
                ('CONFIDENCE', models.FloatField(blank=True, null=True, verbose_name='신뢰도')),
                ('RESULT_MESSAGE', models.TextField(blank=True, null=True, verbose_name='결과 메시지')),
                ('CONFIDENCE_LEVEL', models.CharField(blank=True, max_length=50, null=True, verbose_name='신뢰도 등급')),
                ('TOP_3', models.TextField(blank=True, null=True, verbose_name='TOP 3 결과')),
                ('RECYCLING_GUIDE', models.TextField(blank=True, null=True, verbose_name='처리 가이드')),
                ('RESULT_IMAGE', models.ImageField(blank=True, null=True, upload_to='recyclable_results/', verbose_name='결과 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('group_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='service.groupcode', verbose_name='분류 코드')),
            ],
            options={
                'verbose_name': '분류 결과',
                'verbose_name_plural': '분류 결과 목록',
                'db_table': 'recyclable_result',
                'ordering': ['created_at'],
            },
        ),
        # 초기 데이터 삽입
        migrations.RunPython(create_initial_groupcode),
    ]
