# Generated by Django 5.2.7 on 2025-10-17 07:50
import random
from django.db import migrations


def generate_numeric_code(length=5):
    return f"{random.randint(0, 10**length - 1):0{length}d}"


def create_initial_groupcode(apps, schema_editor):
    GroupCode = apps.get_model('service', 'GroupCode')

    initial_data = [
        ("금속캔", "steel_can1"),
        ("금속캔", "steel_can2"),
        ("금속캔", "steel_can3"),
        ("알루미늄캔", "aluminum_can1"),
        ("알루미늄캔", "aluminum_can2"),
        ("종이", "paper1"),
        ("종이", "paper2"),
        ("페트병", "pet_clear_single1"),
        ("페트병", "pet_clear_single2"),
        ("페트병", "pet_clear_single3"),
        ("페트병", "pet_colored_single1"),
        ("페트병", "pet_colored_single2"),
        ("페트병", "pet_colored_single3"),
        ("플라스틱", "plastic_pe1"),
        ("플라스틱", "plastic_pe2"),
        ("플라스틱", "plastic_pp1"),
        ("플라스틱", "plastic_pp2"),
        ("플라스틱", "plastic_pp3"),
        ("플라스틱", "plastic_ps1"),
        ("플라스틱", "plastic_ps2"),
        ("플라스틱", "plastic_ps3"),
        ("스티로폼", "styrofoam1"),
        ("스티로폼", "styrofoam2"),
        ("비닐", "vinyl"),
        ("유리병", "glass_brown"),
        ("유리병", "glass_green"),
        ("유리병", "glass_clear"),
        ("건전지", "battery"),
        ("형광등", "fluorescent_lamp"),
    ]

    for name, code in initial_data:
        while True:
            numeric_code = generate_numeric_code(5)
            if not GroupCode.objects.filter(numeric_code=numeric_code).exists():
                break
        GroupCode.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "numeric_code": numeric_code,
                "desc": f"{name}"
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_countrypf'),  # 여기 추가 — 이게 핵심입니다.
    ]

    operations = [
        migrations.RunPython(create_initial_groupcode),
    ]
