# Generated by Django 5.2.7 on 2025-10-17 07:50
import random
from django.db import migrations


def generate_numeric_code(length=5):
    return f"{random.randint(0, 10**length - 1):0{length}d}"


def create_initial_groupcode(apps, schema_editor):
    GroupCode = apps.get_model('service', 'GroupCode')

    initial_data = [
        ("금속캔_철캔_1", "steel_can1"),
        ("금속캔_철캔_2", "steel_can2"),
        ("금속캔_철캔_3", "steel_can3"),
        ("금속캔_알루미늄캔_1", "aluminum_can1"),
        ("금속캔_알루미늄캔_2", "aluminum_can2"),
        ("종이_001_종이_1", "paper1"),
        ("종이_001_종이_2", "paper2"),
        ("페트병_001_무색단일_1", "pet_clear_single1"),
        ("페트병_001_무색단일_2", "pet_clear_single2"),
        ("페트병_001_무색단일_3", "pet_clear_single3"),
        ("페트병_002_유색단일_1", "pet_colored_single1"),
        ("페트병_002_유색단일_2", "pet_colored_single2"),
        ("페트병_002_유색단일_3", "pet_colored_single3"),
        ("플라스틱_001_PE_1", "plastic_pe1"),
        ("플라스틱_001_PE_2", "plastic_pe2"),
        ("플라스틱_002_PP_1", "plastic_pp1"),
        ("플라스틱_002_PP_2", "plastic_pp2"),
        ("플라스틱_002_PP_3", "plastic_pp3"),
        ("플라스틱_003_PS_1", "plastic_ps1"),
        ("플라스틱_003_PS_2", "plastic_ps2"),
        ("플라스틱_003_PS_3", "plastic_ps3"),
        ("스티로폼_001_스티로폼_1", "styrofoam1"),
        ("스티로폼_001_스티로폼_2", "styrofoam2"),
        ("비닐_001_비닐", "vinyl"),
        ("유리병_001_갈색", "glass_brown"),
        ("유리병_002_녹색", "glass_green"),
        ("유리병_003_투명", "glass_clear"),
        ("건전지_001_건전지", "battery"),
        ("형광등_001_형광등", "fluorescent_lamp"),
    ]

    for name, code in initial_data:
        while True:
            numeric_code = generate_numeric_code(5)
            if not GroupCode.objects.filter(numeric_code=numeric_code).exists():
                break
        GroupCode.objects.get_or_create(
            name=name,
            defaults={
                "code": code,
                "numeric_code": numeric_code,
                "desc": f"{name} 설명"
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_countrypf'),  # ✅ 여기 추가 — 이게 핵심입니다.
    ]

    operations = [
        migrations.RunPython(create_initial_groupcode),
    ]
