# Generated by Django 5.2.7 on 2025-10-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_initial_groupcode_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypf',
            name='active',
            field=models.BooleanField(default=True, verbose_name='사용여부'),
        ),
        migrations.AlterField(
            model_name='countrypf',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별'),
        ),
    ]
