# Generated by Django 5.2.7 on 2025-11-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_countrypf_active_alter_countrypf_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcode',
            name='name',
            field=models.CharField(max_length=200, verbose_name='코드명(한글)'),
        ),
    ]
